---

 - name: Install docker and docker-compose on amazon instances
   hosts: amazon-services
   become: yes
   become_method: sudo
   become_user: root
   gather_facts: no

   pre_tasks:
     - name: Install minimal python on amazon instances
       raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
       register: output
       changed_when: output.stdout != ""

     - name: Make gathering facts
       setup:

   roles:
     - install-docker
